### ISSUE TITLE
module not working

### ISSUE THREAD

**Issue by Minyar2004** [schlameel/electron-scroller#1]
Hi,

I want to test your module electron-scroller, I'm following steps listed in your description but it does not work for me.

**Comment by schlameel** [comment]
I just tried it and it works.  Unless you can be more specific, I'm afraid I cannot help you.

**Comment by schlameel** [comment]
Actually, I'll make one change to the browser.js code in the example.  The call to `scroller.add()` may need to go inside a function:
```javascript
const scroller = require('electron-scroller')

onload = function() {
  scroller.add()
}
```
